/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class KonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CelciusTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KelvinTxt = new javax.swing.JLabel();
        outputKelvin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FahrenheitTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ReamurTxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        outputReamur = new javax.swing.JTextField();
        inputCelcius = new javax.swing.JTextField();
        outputFahrenheit = new javax.swing.JTextField();
        ButtonKonversi = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonKeluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CelciusTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CelciusTxt.setText("Suhu Celcius");

        jLabel2.setText("'C");

        KelvinTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        KelvinTxt.setText("Suhu Kelvin");

        outputKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputKelvinActionPerformed(evt);
            }
        });

        jLabel4.setText("'K");

        FahrenheitTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FahrenheitTxt.setText("Suhu Fahrenheit");

        jLabel6.setText("'F");

        ReamurTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ReamurTxt.setText("Suhu Reamur");

        jLabel8.setText("'R");

        outputReamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputReamurActionPerformed(evt);
            }
        });

        inputCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCelciusActionPerformed(evt);
            }
        });

        outputFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFahrenheitActionPerformed(evt);
            }
        });

        ButtonKonversi.setText("Konversi");
        ButtonKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKonversiActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonKeluar.setText("Keluar");
        ButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKeluarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLabel9.setText("KONVERSI SUHU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReamurTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(outputReamur, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FahrenheitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KelvinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(outputKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(CelciusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(inputCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(ButtonKonversi)
                .addGap(38, 38, 38)
                .addComponent(ButtonHapus)
                .addGap(44, 44, 44)
                .addComponent(ButtonKeluar)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CelciusTxt)
                        .addComponent(jLabel2))
                    .addComponent(inputCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonKonversi)
                    .addComponent(ButtonKeluar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KelvinTxt)
                    .addComponent(outputKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FahrenheitTxt)
                    .addComponent(jLabel6)
                    .addComponent(outputFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReamurTxt)
                    .addComponent(jLabel8)
                    .addComponent(outputReamur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputKelvinActionPerformed

    private void outputReamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputReamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputReamurActionPerformed

    private void inputCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCelciusActionPerformed

    private void outputFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFahrenheitActionPerformed

    private void ButtonKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKonversiActionPerformed
        // TODO add your handling code here:
        double c,k,f,r;
        
        c = Double.parseDouble(inputCelcius.getText());
        
        k = c + 273.15;
        f = c * 1.8 + 32;
        r = c * 0.8;
        
        outputKelvin.setText(String.valueOf(k));
        outputFahrenheit.setText(String.valueOf(f));
        outputReamur.setText(String.valueOf(r));
    }//GEN-LAST:event_ButtonKonversiActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        inputCelcius.setText("");
        outputKelvin.setText("");
        outputFahrenheit.setText("");
        outputReamur.setText("");
        inputCelcius.requestFocus();
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKeluar;
    private javax.swing.JButton ButtonKonversi;
    private javax.swing.JLabel CelciusTxt;
    private javax.swing.JLabel FahrenheitTxt;
    private javax.swing.JLabel KelvinTxt;
    private javax.swing.JLabel ReamurTxt;
    private javax.swing.JTextField inputCelcius;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField outputFahrenheit;
    private javax.swing.JTextField outputKelvin;
    private javax.swing.JTextField outputReamur;
    // End of variables declaration//GEN-END:variables
}
